# Problem 1

In [5]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 5.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
# 1 - numpy kütüphanesini import edin

import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.array([0, 1, 2, 3, 4])
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
c = np.array([0, 1, 2, 3, 4, 5])
b = c.reshape(2, 3)
print(b)
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[0 1 2 3 4]
(5,)
[[0 1 2]
 [3 4 5]]
1


# Problem 2

In [9]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.array([[1, 3, 5],[7, 9, 11]])

# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(a,[3,5]))
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([a,a]))

[array([[ 1,  3,  5],
       [ 7,  9, 11]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]
[[ 1  3  5]
 [ 7  9 11]
 [ 1  3  5]
 [ 7  9 11]]


# Problem 3

In [12]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.array([i for i in range(1, 101, 2)][::2])
# 2 - matris'in özelliklerini inceleyin
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(25,)
25
int32
