# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([0, 1, 17, 120, 15])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
np.sort(x)

array([  0,   1,  15,  17, 120])

# Problem 2

In [29]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10, 15, 30, 45, 60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
c = np.arange(5, 16)
print(c)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
b = np.arange(50, 105, 5)
print(b)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0, 100, 5)
print(f)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10, 30, 5)
print(g)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.uniform(-1, 1, 10)
print(h)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i = np.random.randint(10, 51, size=(3, 5))
print(i)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_sayisi = i.shape[0]
sutun_sayisi = i.shape[1]
print(f"matrisin satir sayisi {satir_sayisi} dır")
print(f"matrisin sütun sayısı {sutun_sayisi} dır")
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
enbuyuk = np.amax(i)
enkucuk = np.amin(i)
ortalama = np.average(i)
print(f" i matrisinin en büyük değeri {enbuyuk} dur")
print(f"i matrisinin en küçük değeri {enkucuk} dır")
print(f"i matrisinin ortalaması {ortalama} dır")

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
enbuyuk = np.amax(i)
print(f" i matrisinin en büyük değeri {enbuyuk} dur")
enbuyuk_indeks = np.argmax(i)
print(f"oluşturulan i matrisinin en büyük değerinin indeksi {enbuyuk_indeks} dır")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
j = np.arange(10, 21)  
ilkuc = j[:3]  

print("Oluşturulan dizi:", j)
print("Dizinin ilk üç elemanı:", ilkuc)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
j = np.arange(10, 21)  
tersj = j[::-1]  
print("Dizinin ters yazılmış hali:", tersj)
# 15- Üretilen matrisin ilk satırını seçiniz.
j = np.random.randint(10, 21, size=(3, 5))  
ilksatir = j[0, :]

print("Oluşturulan matris:\n", j)
print("Matrisin ilk satırı:", ilksatir)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
j = np.random.randint(10, 21, size=(3, 5))  
secilenler = j[1,2]

print("Oluşturulan matris:\n", j)
print("Matrisin 2. satır 3. sütundaki elemanı:", secilenler)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
j = np.random.randint(10, 21, size=(3, 5))  
ilkler = j[:,0]

print("Oluşturulan matris:\n", j)
print("Matristeki ilk elemanlar:", ilkler)
# 18- Üretilen matrisin her bir elemanının karesini alınız.
j = np.random.randint(10, 21, size=(3, 5))  
kare = j**2

print("Oluşturulan matris:\n", j)
print("Matristeki elemanların kareleri", kare)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
j = np.random.randint(-50, 51, size=(3, 5))  

print("Oluşturulan matris:\n", j)
print("Pozitif çift sayılar:", [x for x in j.flatten() if x > 0 and x % 2 == 0])


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[24 24 13 27 22]
[ 0.62140849  0.43454805  0.12596365 -0.33676278  0.51465554 -0.69801683
 -0.06583346  0.66094855  0.61022994  0.59608813]
[[31 20 23 42 32]
 [27 46 42 32 10]
 [20 36 13 19 47]]
matrisin satir sayisi 3 dır
matrisin sütun sayısı 5 dır
 i matrisinin en büyük değeri 47 dur
i matrisinin en küçük değeri 10 dır
i matrisinin ortalaması 29.333333333333332 dır
 i matrisinin en büyük değeri 47 dur
oluşturulan i matrisinin en büyük değerinin indeksi 14 dır
Oluşturulan dizi: [10 11 12 13 14 15 16 17 18 19 20]
Dizinin ilk üç elemanı: [10 11 12]
Dizinin ters yazılmış hali: [20 19 18 17 16 15 14 13 12 11 10]
Oluşturulan matris:
 [[18 20 15 13 14]
 [19 14 13 11 10]
 [13 14 18 20 12]]
Matrisin ilk satırı: [18 20 15 13 14]
Oluşturulan matris:
 [[14 15 13 13 18]
 [13 13 11 12 13]
 [17 19 12 12 19]]
Mat